#!/usr/bin/env python2
# -*- coding: utf-8 -*- 

import os
import cmd
import sys
import time
import frida
import argparse
import subprocess


class FridaProcess:
    def __init__(self):
        pass

    @staticmethod
    def run():
        cmd_check_frida = 'adb shell "ps; ps -ef" | sort | uniq | grep frida-server | wc -l'
        cmd_start_frida_daemon = 'adb shell "/data/local/tmp/frida-server -D"'

        if subprocess.check_output([cmd_check_frida], shell=True).strip() is '0':
            print('[*] Starting Frida server...')
            subprocess.Popen(cmd_start_frida_daemon, stdin=subprocess.PIPE, shell=True)

            time.sleep(2)

    @staticmethod
    def terminate():
        cmd_kill_frida = 'adb shell "killall -9 frida-server"'
        print('[*] Terminating frida-server...')
        subprocess.Popen(cmd_kill_frida, stdin=subprocess.PIPE, shell=True)


class BadadaShell(cmd.Cmd):
    default_rpc_methods = None
    args = None
    session = None
    script = None
    log = None
    usb_device = None
    child_gating_hooks = {}
    child_gating_sessions = set()

    def __init__(self):
        cmd.Cmd.__init__(self)

        self.aliases = {
            'exit': self.do_quit
        }

        parser = argparse.ArgumentParser(description='Badada arguments')
        parser.add_argument('processToHook', help='Name of the process to be attached')
        parser.add_argument('-j', '--javascript', help='Path to javascript code file to inject')
        parser.add_argument('--log', help='Save output to path')
        parser.add_argument('--spawn', action='store_true', help='Frida injects into Zygote, spawns processToHook '
                                                                 'and waits for input. Similar to running '
                                                                 'Frida with -f flag')

        parser.add_argument('--activity', help='Specify which activity you want to spawn')
        parser.add_argument('--child-gating', action='store_true', help='Monitor the chidren of a process')
        parser.add_argument('--child-gating-args', help='Specify the arguments of '
                                                        'child gating feature')

        self.args = parser.parse_args()
        self.log = self.args.log
        
        print('\033[1m' + '\033[94m' + """                 ____          _____          _____          
                |  _ \   /\   |  __ \   /\   |  __ \   /\    
                | |_) | /  \  | |  | | /  \  | |  | | /  \   
                |  _ < / /\ \ | |  | |/ /\ \ | |  | |/ /\ \  
                | |_) / ____ \| |__| / ____ \| |__| / ____ \ 
                |____/_/    \_\_____/_/    \_\_____/_/    \_\\        
            """ + '\033[0m')

        print('[*] Ensuring adb server is running...')
        subprocess.call(['adb', 'start-server'])

        print('[*] Waiting until the device is connected to the USB port...')
        os.system('adb wait-for-device')

        if self.args.processToHook != 'Gadget':
            print('[*] Checking if frida-server is located at tmp dir...')
            if subprocess.check_output(['adb shell "[ -f /data/local/tmp/frida-server ]; echo \\$?"'],
                                       shell=True).strip() is not '0':

                print('[-] frida-server does not exist in /data/local/tmp/frida-server')
                return

            self.frida_server = FridaProcess()
            self.frida_server.run()
        
        print('[*] Attaching USB Device')

        try:
            self.usb_device = frida.get_usb_device(2)  # timeout = 2

        except frida.TimedOutError:
            print('[-] Failed to attach to USB Device.')
            return

        if not self.usb_device:
            print('[-] Failed to attach to USB Device.')
            return

        try:
            # If is digit, attach to pid
            pid = None

            if self.args.child_gating_args and not self.args.child_gating:
                print('[-] The --child-gating-args option just makes sense when using --child-gating')
                return

            if self.args.child_gating and self.args.child_gating_args:
                self.parse_child_gating_args()

            if self.args.child_gating:
                self.usb_device.on('child-added', lambda child: self.on_child_added(child))

            if self.args.activity and not self.args.spawn:
                print('[-] The --activity option just makes sense when using --spawn')
                return

            if self.args.spawn:
                if self.args.processToHook.isdigit():
                    print('[-] To spawn the process you must pass the process name')
                    return

                if not self.args.activity:
                    print('[*] Spawning %s' % (self.args.processToHook))
                    pid = self.usb_device.spawn([self.args.processToHook])

                else:
                    print('[*] Spawning %s in "%s" activity' % (self.args.processToHook, self.args.activity))
                    pid = self.usb_device.spawn(self.args.processToHook, activity=self.args.activity)

                print('[*] Attaching to %s' % (self.args.processToHook))
                self.session = self.usb_device.attach(pid)

            elif self.args.processToHook.isdigit():
                print('[*] Attaching to ' + self.args.processToHook + " pid")
                self.session = self.usb_device.attach(int(self.args.processToHook))

            else:
                print('[*] Attaching to ' + self.args.processToHook + " process")
                self.session = self.usb_device.attach(self.args.processToHook)

        except frida.ServerNotRunningError:
            print('[-] Unable to connect to frida-server.')
            return

        except frida.ProcessNotFoundError:
            print('[-] Unable to find ' + self.args.processToHook + ' to attach.')
            return

        if self.args.child_gating:
            self.session.enable_child_gating()

        print('[*] Loading default RPC methods')
        self.default_rpc_methods = self.load_script(os.path.join(
            os.path.dirname(__file__), 'scripts/', 'scriptsRPC.js'))

        self.script = None

        if self.args.javascript:
            print('[*] Loading %s' % (self.args.javascript))
            try:
                self.script = self.load_script(self.args.javascript)

            except IOError:
                print('[-] Unable to load script "' + self.args.javascript + '": file not found.')
                self.script = None
                self.args.javascript = None

        if self.args.spawn:
            print('[*] Resuming %s' % (self.args.processToHook))
            time.sleep(1)
            self.usb_device.resume(pid)

    def parse_child_gating_args(self):
        print('[*] Parsing Child Gating Args...')

        dict_hooks = {}
        try:
            args = self.args.child_gating_args.split(' ')

            for arg in args:
                app, hook_file = arg.split('=')
                print("[+] Child-Gating parser - APP: " + str(app) + ' HOOK: ' + str(hook_file))

                if not os.path.isfile(hook_file):
                    print('[-] File %s not found' % (hook_file))
                    raise Exception('Argument Parsing error')

                dict_hooks[app] = hook_file

        except Exception:
            print('[-] Error while parsing --child-gating-args')
            print(self.args.child_gating_args)
            print('How to use --child-gating-args:')
            print("badada process_to_hook --child-gating "
                  "--child-gating-args='org.mozilla.firefox=firefoxhook.js com.android.chrome=chromehook.js'")

            dict_hooks = {}

        self.child_gating_hooks = dict_hooks

    def on_child_removed(self, reason, session, child):
        print('\n[*] Child Removed (%s): %s' % (reason, child.identifier))
        self.child_gating_sessions.remove(session)

    def on_child_added(self, child):
        print('\n[*] New Child: %s (PID: %s | PPID: %s)' % (child.identifier, child.pid, child.parent_pid))

        if child.identifier in self.child_gating_hooks.keys():
            print('[*] Hooking %s' % (child.identifier))
            session = self.usb_device.attach(child.pid)
            session.on('detached', lambda reason: self.on_child_removed(reason, session, child))
            session.enable_child_gating()

            hook_source = self.get_file_contents(self.child_gating_hooks[child.identifier])
            self.script = session.create_script(hook_source)
            self.script.on('message', self.on_message)
            self.script.load()

            self.child_gating_sessions.add(session)

        self.usb_device.resume(child.pid)

    def emptyline(self):
        pass

    def default(self, line):
        command, arg, line = self.parseline(line)

        if line[0] is '!':
            os.system(line[1:])
        elif command in self.aliases:
            self.aliases[command](arg)
        else:
            print('[-] Command not found')

    @staticmethod
    def get_file_contents(file_name):
        f = open(file_name)
        content = f.read()
        f.close()

        return content

    def on_message(self, message, data):
        if 'payload' in message.keys():
            if self.log:
                log_file = open("logs/" + self.log, 'a')
                log_file.write(str(time.asctime()))
                log_file.write(" ---> ")
                log_file.write(str(message['payload']) + '\n')
                log_file.close()
            sys.stdout.write(str(message['payload']) + '\n')
        else:
            if self.log:
                log_file = open("logs/" + self.log, 'a')
                log_file.write(str(time.asctime()))
                log_file.write(" ---> ")
                log_file.write(str(message) + '\n')
                log_file.close()
            sys.stdout.write(str(message) + '\n')

    def load_script(self, file_name):
        hook_source = self.get_file_contents(file_name)
        self.script = self.session.create_script(hook_source)
        self.script.on('message', self.on_message)
        self.script.load()

        return self.script

    def get_classes(self, contains_text):
        if not self.default_rpc_methods:
            print('[-] Seems that there is no hook')
            return

        self.default_rpc_methods.exports.getclasses(contains_text)

    def get_methods_with_signature(self, class_name, contains_text):
        if not self.default_rpc_methods:
            print('[-] Seems that there is no hook')
            return

        self.default_rpc_methods.exports.getmethods(class_name, contains_text)

    def search_method(self, method_name):
        if not self.default_rpc_methods:
            print('[-] Seems that there is no hook')
            return
      
        self.default_rpc_methods.exports.searchmethod(method_name)
    
    def cleanup(self):
        print('[*] Detaching from childs...')

        for child_session in list(self.child_gating_sessions):
            child_session.detach()

        if self.default_rpc_methods:
            print('[*] Unloading default RPC methods')
            try:
                self.default_rpc_methods.unload()
            except frida.InvalidOperationError:
                pass
            finally:
                self.default_rpc_methods = None

        if self.script:
            print('[*] Unloading current script...')
            try:
                self.script.unload()
            except frida.InvalidOperationError:
                pass
            finally:
                self.script = None

        print('[*] Detaching current session.')
        if self.session is not None:
            try:
                self.session.detach()
            except frida.InvalidOperationError:
                pass
            finally:
                self.session = None
    
        print('[*] Exiting...\n' + '[*] Thanks for using Badada! ' + 'Bye \\o/')

    def do_quit(self, in_args):
        raise SystemExit

    @staticmethod
    def help_quit():
        print('\n'.join(['Exit Frida']))

    def do_reload(self, in_args):
        if not self.args.javascript:
            print('[*] There is no script to reload.')
            return
        
        if self.script:
            print('[*] Unloading current script...')
            self.script.unload()
            self.script = None

        print('[*] Reloading %s' % (self.args.javascript))
        try:
            self.script = self.load_script(self.args.javascript)
        except IOError:
            print('[-] Unable load script "' + self.args.javascript + '": file not found.')
            self.script = None

    @staticmethod
    def help_reload():
        print('\nReloads current script for changes\n')

    def do_unload(self, in_args):
        if self.args.javascript and self.script:
            print('[*] Unloading current script...')
            self.script.unload()
            self.script = None
        else:
            print('[-] There is no script to unload')

    def do_load(self, in_args):
        args = in_args.strip().split(" ")
        if len(args) != 1 or len(args[0]) == 0:
            print('\n[-] Usage load [<script.js>]\n')

        else:
            if self.args.javascript and self.script:
                print('[*] Unloading current script...')
                self.script.unload()
                self.script = None
            
            print('[*] Loading new script...')
            self.args.javascript = args[0]
            
            try:
                self.script = self.load_script(self.args.javascript)
            except IOError:
                print('[-] Unable load script "' + self.args.javascript + '": file not found.')
                self.script = None

    @staticmethod
    def help_load():
        print('\nLoads a javascript code to be injected.\n')

    def do_classes(self, in_args):
        args = in_args.strip().split(" ")
        if len(args) > 1:
                print('\n[-] Usage getclasses [<contains_this>]')

        elif len(args) == 0:
            self.get_classes('')

        else:
            self.get_classes(args[0])

    @staticmethod
    def help_searchmethod():
        print('\n'.join(['Iterate in all classes, looking for a specific method']))

    def do_searchmethod(self, method_name):
        if not method_name:
            print('\nYou have to specify a method to search for')
            return

        self.search_method(method_name)

    def help_classes(self):
        print '\n'.join(['Show all classes filtered by [<contains_this>]'])

    @staticmethod
    def help_classes():
        print('\n'.join(['Show all classes filtered by [<contains_this>]']))

    def do_methods(self, in_args):
        args = in_args.strip().split(" ")
        if len(args) < 1:
            print('\n[-] Usage: getmethods <className> [<contains_this>]\n')

        elif len(args) == 1:
            self.get_methods_with_signature(args[0], "")
        else:
            self.get_methods_with_signature(args[0], args[1])

    def help_methods(self):
        print '\n'.join(['Show all methods from <class_name> [<contains_this>]'])

    @staticmethod
    def help_methods():
        print('\n'.join(['Show all methods from <class_name> [<contains_this>]']))

    @staticmethod
    def help_clear():
        print('\n'.join(['Clears the terminal screen.']))

    def do_hook(self, in_args):
        args = in_args.strip().split(" ")
        if len(args) < 1 or len(args[0]) == 0:
            print('\n[-] Usage hook <process_to_hook>\n')

        else:
            if self.default_rpc_methods:
                print('[*] Unloading default RPC methods')
                try:
                    self.default_rpc_methods.unload()
                except frida.InvalidOperationError:
                    pass
                finally:
                    self.default_rpc_methods = None

            if self.args.javascript and self.script:
                print('[*] Unloading current script...')
                self.script.unload()
                self.script = None

            print('[*] Detaching current session.')
            self.session.detach()

            print('[*] Attaching to ' + args[0] + '.')

            try:
                self.session = self.usb_device.attach(args[0])
                self.default_rpc_methods = self.load_script(
                    os.path.join(os.path.dirname(__file__), 'scripts/', 'scriptsRPC.js'))

                self.args.javascript = None
            except frida.ServerNotRunningError:
                print('[-] Unable to connect to frida-server.')
                return
            except frida.ProcessNotFoundError:
                print('[-] Unable to find the process to attach.')

    @staticmethod
    def help_hook():
        print('\n'.join(['Hooks a new process']))


if __name__ == '__main__':
    prompt = BadadaShell()
    prompt.prompt = '\033[1m' + '\033[92m' + 'badada> ' + '\033[0m'

    try:
        prompt.cmdloop()
    except KeyboardInterrupt as err:
        print('[*] CTRL+C detected...')
    except Exception as e:
        print('[-] %s' % (e.message.capitalize()))
    finally:
        prompt.cleanup()
